users_auth/basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name='register' ),
    path('user_login/', views.user_login, name='user_login'),
]

users_auth/users_auth/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic-app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
]

users_auth/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, models.CASCADE)

    # additional fields
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics/', blank=True)

    def __str__(self) -> str:
        return self.user.username
    

users_auth/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

users_auth/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

# 
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return JsonResponse({"message": "You are already logged in . Nice! "})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False
    if request.method=="POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            
            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html', {'registered':registered,'profile_form':profile_form,'user_form':user_form})

def user_login(request):

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(redirect_to=reverse('index'))
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
            
        else:
            print("LOGIN FAILED!!")
            print(f"Username: {username}, Password: {password}")
            return HttpResponse("INVALID LOGIN DETAILS!!")
    else:
        return render(request, 'basic_app/login.html')

users_auth/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title> </title>
</head>
<body>
    <div class="container">
    <header class="d-flex justify-content-center py-3">
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a href="{% url 'index' %}" class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page">Home</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'admin:index' %}" class="nav-link">Admin</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'basic_app:register' %}" class="nav-link {% if 'register' in request.path %}active{% endif %}">Register</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a href="{% url 'special' %}" class="nav-link {% if 'special' in request.path %}active{% endif %}">Special</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'logout' %}" class="nav-link {% if 'logout' in request.path %}active{% endif %}">Logout</a>
            </li>
            {% else %}
                <li class="nav-item">
                    <a href="{% url 'basic_app:user_login' %}" class="nav-link {% if 'login' in request.path %}active{% endif %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </header>
    
      </div>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

users_auth/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1> Django level 5 </h1>
</div>


{% endblock %}

users_auth/templates/basic_app/login.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1>Please Login </h1>
    <form action="{% url 'basic_app:user_login' %}" method="post">
        {% csrf_token %}
        <label for="username">Username: </label>
        <input type="text" name="username" placeholder="Enter username">

        <label for="password">Password: </label>
        <input type="password" name="password" placeholder="Enter password">

        <input type="submit" value="Login">
    </form>
</div>


{% endblock %}

users_auth/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1> Thanks for registering! </h1>
    {% else %}
        <h1>Register Here</h1>
        <h3>Fill out the form: </h3>
        <form action="" enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            <input type="submit" value="Register">
        </form>
    {% endif %}
</div>

{% endblock %}