learn_templates/basic_app/urls.py
from . import views
from django.urls import path

app_name = 'basic_app'

urlpatterns = [
    path('other/', views.other, name='other'),
    path('relative/', views.relative, name='relative'),
]

learn_templates/learn_templates/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('basic-app/', include('basic_app.urls')),
    path('admin/', admin.site.urls),
]

learn_templates/basic_app/models.py
from django.db import models

# Create your models here.

learn_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    dic = {'text':'Hello World!', 'num': 12345 }
    return render(request, 'basic_app/index.html', dic)

def other(request):
    return render(request, 'basic_app/other.html')

def relative(request):
    return render(request, 'basic_app/relative_url_templates.html')

learn_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>Base </title>
</head>
<body>
    <div class="container">
    <header class="d-flex justify-content-center py-3">
        <ul class="nav nav-pills">
            <li class="nav-item">
                <a href="{% url 'index' %}" class="nav-link {% if request.path == '/' %}active{% endif %}" aria-current="page">Home</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'admin:index' %}" class="nav-link">Admin</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'basic_app:other' %}" class="nav-link {% if '/other/' in request.path %}active{% endif %}">Other</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'basic_app:relative' %}" class="nav-link {% if '/relative/' in request.path %}active{% endif %}">Relative</a>
            </li>
        </ul>
    </header>
    
      </div>

    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

learn_templates/templates/basic_app/index.html
{% extends 'basic_app/base.html' %}
{% load my_extras %}
    {% block body_block %}
    <h1>Welcome to home page </h1>
    <h3> This is index page using templates </h3>
    <h5>
        This text got cut using custom filters: 
        {{text | cut:'ello'}}
    </h5>
    <p>       
        The sum of {{num}} and 765 is {{num | add:765}}.<br>
    </p>
    {% endblock %}

learn_templates/templates/basic_app/other.html
{% extends 'basic_app/base.html' %}
    {% block body_block %}
    <h1>Welcome to Other page</h1>
    <h3>Using template tagging . It's so cool. </h3>
    {% endblock %}

learn_templates/templates/basic_app/relative_url_templates.html
{% extends 'basic_app/base.html' %}
    {% block body_block %}
    <h1>Welcome to Relative url template page</h1>
    <ul>
        <li>
            <a href="{% url 'basic_app:other' %}">Go to other page.</a>
        </li>
        <li>
            <a href="{% url 'admin:index' %}">Go to admin page.</a>
        </li>
        <li>
            <a href="{% url 'index' %}">Go to home page.</a>
        </li>
    </ul>

    {% endblock %}
    